apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: tailscale
spec:
  title: 'tailscale'
  url: 'https://tailscale.com/'
  gitRepo: 'https://github.com/tailscale/tailscale'
  author: 'ripples'
  description: 'Tailscale - Private WireGuard® networks made easy'
  readme: 'https://github.com/tailscale/tailscale/blob/main/README.md'
  icon: 'https://tailscale.com/favicon.png'
  templateType: inline
  categories:
    - tool
  defaults:
    app_host:
      type: string
      value: ${{ random(8) }}
    app_name:
      type: string
      value: tailscale-${{ random(8) }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: tailscale/tailscale
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  serviceName: ${{ defaults.app_name }}
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      terminationGracePeriodSeconds: 10
      automountServiceAccountToken: false
      containers:
        - name: ${{ defaults.app_name }}
          image: tailscale/tailscale
          env: []
          resources:
            requests:
              cpu: 10m
              memory: 6Mi
            limits:
              cpu: 100m
              memory: 64Mi
          command:
            - tailscaled
            - '-tun'
            - userspace-networking
          args: []
          ports: []
          imagePullPolicy: Always
          volumeMounts:
            - name: vn-varvn-libvn-tailscale
              mountPath: /var/lib/tailscale
      volumes: []
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /var/lib/tailscale
          value: '0.05'
        name: vn-varvn-libvn-tailscale
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 64Mi
