apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: ubuntu-persistent
spec:
  title: 'ubuntu-persistent'
  url: 'https://github.com/ripples-alive/ubuntu-persistent'
  gitRepo: 'https://github.com/ripples-alive/ubuntu-persistent'
  author: 'ripples'
  description: 'Ubuntu image with persistent system volumes'
  readme: 'https://raw.githubusercontent.com/ripples-alive/templates/main/template/ubuntu-persistent/README.md'
  icon: 'https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/ubuntu/ubuntu.png'
  templateType: inline
  categories:
    - tool
  defaults:
    app_name:
      type: string
      value: ubuntu-persistent-${{ random(8) }}
  inputs:
    CPU_LIMIT:
      description: 'cpu limit'
      type: string
      default: '1'
      required: true
    MEMORY_LIMIT:
      description: 'memory limit (Gi)'
      type: string
      default: '1'
      required: true
    SSH_PUBKEY:
      description: 'ssh public key'
      type: string
      default: ''
      required: false
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: ripples/ubuntu-persistent:24.04
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  serviceName: ${{ defaults.app_name }}
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      terminationGracePeriodSeconds: 10
      automountServiceAccountToken: false
      containers:
        - name: ${{ defaults.app_name }}
          image: ripples/ubuntu-persistent:24.04
          env:
            - name: SSH_PUBKEY
              value: ${{ inputs.SSH_PUBKEY }}
          resources:
            requests:
              cpu: 100m
              memory: 102Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: ${{ inputs.CPU_LIMIT }}
              memory: ${{ inputs.MEMORY_LIMIT }}Gi
              ephemeral-storage: 10Gi
          command: []
          args: []
          ports:
            - containerPort: 22
          imagePullPolicy: Always
          volumeMounts:
            - name: vn-appvn-etc
              mountPath: /etc
            - name: vn-appvn-home
              mountPath: /home
            - name: vn-appvn-opt
              mountPath: /opt
            - name: vn-appvn-root
              mountPath: /root
            - name: vn-appvn-usr
              mountPath: /usr
            - name: vn-appvn-var
              mountPath: /var
      volumes: []
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /etc
          value: '1'
        name: vn-appvn-etc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    - metadata:
        annotations:
          path: /home
          value: '1'
        name: vn-appvn-home
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    - metadata:
        annotations:
          path: /opt
          value: '1'
        name: vn-appvn-opt
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    - metadata:
        annotations:
          path: /root
          value: '1'
        name: vn-appvn-root
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    - metadata:
        annotations:
          path: /usr
          value: '1'
        name: vn-appvn-usr
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    - metadata:
        annotations:
          path: /var
          value: '1'
        name: vn-appvn-var
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  type: NodePort
  ports:
    - port: 22
      targetPort: 22
  selector:
    app: ${{ defaults.app_name }}
